const $=s=>document.querySelector(s), html=$('#html'),css=$('#css'),js=$('#js'),frame=$('#preview'),info=$('#info'),status=$('#status');
let state={html:'',css:'',js:'',doc:null,nodes:[],cssRules:[],selected:null,names:{html:'',css:'',js:''}};
const SIMPLE_HTML=`<!doctype html>\n<html>\n<head>\n  <title>Meatball Fan Page</title>\n</head>\n<body>\n  <h1>Meatball is a Good Boy</h1>\n  <p>Meatball is a <b>very good</b> little dog.</p>\n  <p>He is <i>stylish</i>, <u>handsome</u>, and excellent at snacks.</p>\n  <img src="oz.jpg" alt="A very good dog" width="180">\n  <h2>Meatball likes:</h2>\n  <ul><li>Treats</li><li>Naps</li><li>Walks</li></ul>\n  <a href="https://example.com">A link that xrayOz will inspect, not open</a>\n</body>\n</html>`;
const FULL_CSS=`body { font-family: Arial; padding: 25px; background: #fff7df; }\nh1 { color: #8b4513; font-size: 32px; }\nbutton { margin: 5px; padding: 8px; }\n#counter { font-weight: bold; }`;
const FULL_HTML=`<!doctype html>\n<html><head><title>Interactive Meatball</title></head><body>\n<h1 id="title">Meatball is a Good Boy</h1>\n<p id="message">JavaScript can change this page.</p>\n<img src="oz.jpg" alt="Oz" width="180">\n<p><b>HTML</b> gives the page structure. <i>CSS</i> styles it. <u>JavaScript</u> makes it react.</p>\n<button id="textBtn">Change the text</button>\n<button id="colorBtn">Change the color</button>\n<button id="countBtn">Count clicks</button>\n<p>Clicks: <span id="counter">0</span></p>\n</body></html>`;
const FULL_JS=`const title = document.getElementById('title');\nconst message = document.getElementById('message');\nconst counter = document.getElementById('counter');\nlet clicks = 0;\ndocument.getElementById('textBtn').addEventListener('click', () => { message.textContent = 'Meatball says hello from JavaScript!'; });\ndocument.getElementById('colorBtn').addEventListener('click', () => { title.style.color = title.style.color === 'blue' ? '#8b4513' : 'blue'; });\ndocument.getElementById('countBtn').addEventListener('click', () => { clicks++; counter.textContent = clicks; });`;
function esc(s){return s.replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}
function paintCode(el,text,empty){el.innerHTML='';(text||empty).split('\n').forEach((line,i)=>{let s=document.createElement('span');s.className='line';s.dataset.line=i;s.textContent=line||' ';el.appendChild(s)})}
function splitHTML(src){let p=new DOMParser().parseFromString(src,'text/html');let embeddedCSS=[...p.querySelectorAll('style')].map(x=>x.textContent).join('\n\n');let embeddedJS=[...p.querySelectorAll('script')].filter(x=>!x.src).map(x=>x.textContent).join('\n\n');return {p,embeddedCSS,embeddedJS}}
function compose(){let p=new DOMParser().parseFromString(state.html||'<html><body></body></html>','text/html');p.querySelectorAll('style[data-xray-added],script[data-xray-added]').forEach(x=>x.remove());if(state.css){let st=p.createElement('style');st.dataset.xrayAdded='1';st.textContent=state.css;p.head.appendChild(st)}if(state.js){let sc=p.createElement('script');sc.dataset.xrayAdded='1';sc.textContent=state.js;p.body.appendChild(sc)}let n=0;[...p.body.querySelectorAll('*')].forEach(e=>{if(e.tagName!=='SCRIPT')e.dataset.xrayId=String(n++)});let guard=p.createElement('script');guard.textContent=`document.addEventListener('click',e=>{let a=e.target.closest('a');if(a)e.preventDefault();let el=e.target.closest('[data-xray-id]');if(el)parent.postMessage({type:'xray-select',id:el.dataset.xrayId},'*')},true);addEventListener('message',e=>{if(e.data.type==='xray-highlight'){document.querySelectorAll('[data-xray-id]').forEach(x=>x.style.outline='');let x=document.querySelector('[data-xray-id="'+e.data.id+'"]');if(x){x.style.outline='3px solid #f59e0b';x.style.outlineOffset='2px';x.scrollIntoView({block:'nearest'})}}});`;p.body.appendChild(guard);return '<!doctype html>\n'+p.documentElement.outerHTML}
function refresh(label){let x=splitHTML(state.html);state.doc=x.p;state.nodes=[...x.p.body.querySelectorAll('*')];paintCode(html,state.html,'<!-- Upload an HTML file -->');paintCode(css,state.css||x.embeddedCSS,'/* No custom CSS found. */');paintCode(js,state.js||x.embeddedJS,'// No JavaScript found.');buildMaps(state.css||x.embeddedCSS);frame.srcdoc=compose();status.textContent=label;clearSel();updateButtons()}
function buildMaps(t){state.cssRules=[];let re=/([^{}]+)\{([^{}]*)\}/g,m;while((m=re.exec(t)))state.cssRules.push({selector:m[1].trim(),body:m[2].trim()})}
function clearSel(){document.querySelectorAll('.sel,.cssmatch').forEach(x=>x.classList.remove('sel','cssmatch'));state.selected=null;info.innerHTML='<b>Nothing selected.</b> Click something in the website or its code to x-ray it.';try{frame.contentWindow.postMessage({type:'xray-highlight',id:null},'*')}catch(e){}}
function explain(tag){return ({H1:'a main heading',H2:'a section heading',P:'a paragraph',B:'bold text',STRONG:'important/bold text',I:'italic text',EM:'emphasized/italic text',U:'underlined text',IMG:'an image',A:'a link',UL:'an unordered list',OL:'an ordered list',LI:'a list item',BUTTON:'a clickable button',SPAN:'an inline piece of content'})[tag]||'an HTML element'}
function selectId(id){id=+id;let el=state.nodes[id];if(!el)return;state.selected=id;document.querySelectorAll('.sel,.cssmatch').forEach(x=>x.classList.remove('sel','cssmatch'));frame.contentWindow.postMessage({type:'xray-highlight',id:String(id)},'*');let lines=[...html.querySelectorAll('.line')],tag=el.tagName.toLowerCase();let hit=lines.find(x=>x.textContent.toLowerCase().includes('<'+tag)&&(el.id?x.textContent.includes(el.id):true));if(hit){hit.classList.add('sel');hit.scrollIntoView({block:'center'})}let matched=[];for(let r of state.cssRules){try{if(el.matches(r.selector)){matched.push(r);[...css.querySelectorAll('.line')].filter(x=>x.textContent.includes(r.selector)).forEach(x=>x.classList.add('cssmatch'))}}catch(e){}}let jt=state.js||splitHTML(state.html).embeddedJS,j=[];if(el.id&&jt.includes(el.id))j.push(`JavaScript mentions #${el.id}.`);info.innerHTML=`<b>&lt;${tag}&gt;</b> is ${explain(el.tagName)}. `+(matched.length?`CSS matched: <b>${matched.map(x=>esc(x.selector)).join(', ')}</b>.`:'No custom CSS rule was confidently matched; browser defaults or inherited styles may be in use.')+(j.length?' '+j.join(' '):' No direct JavaScript connection was identified.')}
function updateButtons(){[['htmlBtn','html'],['cssBtn','css'],['jsBtn','js']].forEach(([id,k])=>{let b=$('#'+id),pretty=k==='js'?'JavaScript':k.toUpperCase();b.classList.toggle('loaded',!!state[k]);b.textContent=state[k]?`✓ ${pretty} Loaded`:`Upload ${pretty}`})}
function readFile(input,key){let f=input.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{if(key==='html'){state.html=r.result;let x=splitHTML(state.html);state.css=x.embeddedCSS;state.js=x.embeddedJS}else state[key]=r.result;state.names[key]=f.name;refresh(`Loaded ${f.name}`)};r.readAsText(f);input.value=''}
function tray(which){let a=$('#uploadTray'),b=$('#exampleTray'),ua=$('#uploadSite'),eb=$('#exampleSite');if(which==='upload'){a.classList.toggle('open');b.classList.remove('open');ua.classList.toggle('active',a.classList.contains('open'));eb.classList.remove('active')}else{b.classList.toggle('open');a.classList.remove('open');eb.classList.toggle('active',b.classList.contains('open'));ua.classList.remove('active')}}
window.addEventListener('message',e=>{if(e.source===frame.contentWindow&&e.data?.type==='xray-select')selectId(e.data.id)});
html.addEventListener('click',e=>{let line=e.target.closest('.line');if(!line)return;let txt=line.textContent.trim(),m=txt.match(/^<([a-z][\w-]*)(?:\s[^>]*)?>/i);if(!m)return;let candidates=state.nodes.filter(x=>x.tagName.toLowerCase()===m[1].toLowerCase());if(candidates.length===1)selectId(state.nodes.indexOf(candidates[0]));else{let idm=txt.match(/id=["']([^"']+)/i),el=idm&&state.doc.getElementById(idm[1]);if(el)selectId(state.nodes.indexOf(el))}});
css.addEventListener('click',e=>{let line=e.target.closest('.line');if(!line)return;let selector=line.textContent.split('{')[0].trim();if(!selector)return;try{let matches=state.nodes.filter(x=>x.matches(selector));document.querySelectorAll('.cssmatch').forEach(x=>x.classList.remove('cssmatch'));line.classList.add('cssmatch');matches.forEach(x=>frame.contentWindow.postMessage({type:'xray-highlight',id:String(state.nodes.indexOf(x))},'*'));info.innerHTML=`CSS selector <b>${esc(selector)}</b> matches ${matches.length} element${matches.length===1?'':'s'}.`}catch(e){}});
$('#uploadSite').onclick=()=>tray('upload');$('#exampleSite').onclick=()=>tray('example');
$('#htmlBtn').onclick=()=>$('#htmlFile').click();$('#cssBtn').onclick=()=>$('#cssFile').click();$('#jsBtn').onclick=()=>$('#jsFile').click();
$('#htmlFile').onchange=e=>readFile(e.target,'html');$('#cssFile').onchange=e=>readFile(e.target,'css');$('#jsFile').onchange=e=>readFile(e.target,'js');
$('#simpleBtn').onclick=()=>{state.html=SIMPLE_HTML;state.css='';state.js='';refresh('Loaded example: Simple Site')};
$('#fullBtn').onclick=()=>{state.html=FULL_HTML;state.css=FULL_CSS;state.js=FULL_JS;refresh('Loaded example: Full Site')};$('#clear').onclick=clearSel;
paintCode(html,'','<!-- Upload HTML or choose an example -->');paintCode(css,'','/* Upload CSS or choose an example */');paintCode(js,'','// Upload JavaScript or choose an example');frame.srcdoc='<body style="font-family:Arial;padding:30px"><h2>Nothing loaded yet.</h2><p>Use Upload Site or Example Site above.</p></body>';updateButtons();
