const $=s=>document.querySelector(s), html=$('#html'),css=$('#css'),js=$('#js'),frame=$('#preview'),info=$('#info'),status=$('#status');
let state={source:'',doc:null,nodes:[],cssRules:[],selected:null};
const BASIC=`<!doctype html>\n<html>\n<head>\n  <title>Meatball Fan Page</title>\n</head>\n<body>\n  <h1>Meatball is a Good Boy</h1>\n  <p>Meatball is a <b>very good</b> little dog.</p>\n  <p>He is <i>stylish</i>, <u>handsome</u>, and excellent at snacks.</p>\n  <img src="oz.jpg" alt="A very good dog" width="180">\n  <h2>Meatball likes:</h2>\n  <ul><li>Treats</li><li>Naps</li><li>Walks</li></ul>\n  <a href="https://example.com">A link that xrayOz will inspect, not open</a>\n</body>\n</html>`;
const INTER=`<!doctype html>\n<html><head><title>Interactive Meatball</title><style>\nbody { font-family: Arial; padding: 25px; background: #fff7df; }\nh1 { color: #8b4513; font-size: 32px; }\nbutton { margin: 5px; padding: 8px; }\n#counter { font-weight: bold; }\n</style></head><body>\n<h1 id="title">Meatball is a Good Boy</h1>\n<p id="message">JavaScript can change this page.</p>\n<button id="textBtn">Change the text</button>\n<button id="colorBtn">Change the color</button>\n<button id="countBtn">Count clicks</button>\n<p>Clicks: <span id="counter">0</span></p>\n<script>\nconst title = document.getElementById('title');\nconst message = document.getElementById('message');\nconst counter = document.getElementById('counter');\nlet clicks = 0;\ndocument.getElementById('textBtn').addEventListener('click', () => { message.textContent = 'Meatball says hello from JavaScript!'; });\ndocument.getElementById('colorBtn').addEventListener('click', () => { title.style.color = title.style.color === 'blue' ? '#8b4513' : 'blue'; });\ndocument.getElementById('countBtn').addEventListener('click', () => { clicks++; counter.textContent = clicks; });\n</script></body></html>`;
function esc(s){return s.replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}
function paintCode(el,text,type){el.innerHTML=''; text.split('\n').forEach((line,i)=>{let s=document.createElement('span');s.className='line';s.dataset.line=i;s.textContent=line||' ';el.appendChild(s)});}
function extract(src){let p=new DOMParser().parseFromString(src,'text/html');let styles=[...p.querySelectorAll('style')].map(x=>x.textContent).join('\n\n');let scripts=[...p.querySelectorAll('script')].map(x=>x.textContent).join('\n\n');return {p,styles,scripts}}
function instrument(src){let p=new DOMParser().parseFromString(src,'text/html');let n=0;[...p.body.querySelectorAll('*')].forEach(e=>e.dataset.xrayId=String(n++));let guard=p.createElement('script');guard.textContent=`document.addEventListener('click',e=>{let a=e.target.closest('a');if(a)e.preventDefault();let el=e.target.closest('[data-xray-id]');if(el)parent.postMessage({type:'xray-select',id:el.dataset.xrayId},'*')},true);addEventListener('message',e=>{if(e.data.type==='xray-highlight'){document.querySelectorAll('[data-xray-id]').forEach(x=>x.style.outline='');let x=document.querySelector('[data-xray-id="'+e.data.id+'"]');if(x){x.style.outline='3px solid #f59e0b';x.style.outlineOffset='2px';x.scrollIntoView({block:'nearest'})}}});`;p.body.appendChild(guard);return '<!doctype html>\n'+p.documentElement.outerHTML}
function load(src,label){state.source=src;let x=extract(src);state.doc=x.p;state.nodes=[...x.p.body.querySelectorAll('*')];paintCode(html,src,'html');paintCode(css,x.styles||'/* No custom CSS found. */','css');paintCode(js,x.scripts||'// No JavaScript found.','js');frame.srcdoc=instrument(src);status.textContent='Loaded: '+label;clearSel();buildMaps(x.styles,x.scripts)}
function buildMaps(cssText,jsText){state.cssRules=[];let re=/([^{}]+)\{([^{}]*)\}/g,m;while((m=re.exec(cssText)))state.cssRules.push({selector:m[1].trim(),body:m[2].trim()})}
function clearSel(){document.querySelectorAll('.sel,.cssmatch').forEach(x=>x.classList.remove('sel','cssmatch'));state.selected=null;info.innerHTML='<b>Nothing selected.</b> Click something in the website or its code to x-ray it.';try{frame.contentWindow.postMessage({type:'xray-highlight',id:null},'*')}catch(e){}}
function explain(tag){return ({H1:'a main heading',H2:'a section heading',P:'a paragraph',B:'bold text',STRONG:'important/bold text',I:'italic text',EM:'emphasized/italic text',U:'underlined text',IMG:'an image',A:'a link',UL:'an unordered list',OL:'an ordered list',LI:'a list item',BUTTON:'a clickable button',SPAN:'an inline piece of content'})[tag]||'an HTML element'}
function selectId(id){id=+id;let el=state.nodes[id];if(!el)return;state.selected=id;document.querySelectorAll('.sel,.cssmatch').forEach(x=>x.classList.remove('sel','cssmatch'));frame.contentWindow.postMessage({type:'xray-highlight',id:String(id)},'*');let lines=[...html.querySelectorAll('.line')], tag=el.tagName.toLowerCase();let needle='<'+tag, hit=lines.find(x=>x.textContent.toLowerCase().includes(needle) && (el.id?x.textContent.includes(el.id):true));if(hit){hit.classList.add('sel');hit.scrollIntoView({block:'center'})}let matched=[];for(let r of state.cssRules){try{if(el.matches(r.selector)){matched.push(r);[...css.querySelectorAll('.line')].filter(x=>x.textContent.includes(r.selector)).forEach(x=>x.classList.add('cssmatch'))}}catch(e){}}let jsText=[...js.querySelectorAll('.line')].map(x=>x.textContent).join('\n');let j=[];if(el.id&&jsText.includes(el.id))j.push(`JavaScript mentions #${el.id}.`);info.innerHTML=`<b>&lt;${tag}&gt;</b> is ${explain(el.tagName)}. `+(matched.length?`CSS matched: <b>${matched.map(x=>esc(x.selector)).join(', ')}</b>.`:'No custom CSS rule was confidently matched; browser defaults or inherited styles may be in use.')+(j.length?' '+j.join(' '):' No direct JavaScript connection was identified.');}
window.addEventListener('message',e=>{if(e.source===frame.contentWindow&&e.data?.type==='xray-select')selectId(e.data.id)});
html.addEventListener('click',e=>{let line=e.target.closest('.line');if(!line)return;let txt=line.textContent.trim(),m=txt.match(/^<([a-z][\w-]*)(?:\s[^>]*)?>/i);if(!m)return;let candidates=state.nodes.filter(x=>x.tagName.toLowerCase()===m[1].toLowerCase());if(candidates.length===1)selectId(state.nodes.indexOf(candidates[0]));else{let idm=txt.match(/id=["']([^"']+)/i);let el=idm&&state.doc.getElementById(idm[1]);if(el)selectId(state.nodes.indexOf(el));}});
css.addEventListener('click',e=>{let line=e.target.closest('.line');if(!line)return;let selector=line.textContent.split('{')[0].trim();if(!selector)return;try{let matches=state.nodes.filter(x=>x.matches(selector));document.querySelectorAll('.cssmatch').forEach(x=>x.classList.remove('cssmatch'));line.classList.add('cssmatch');matches.forEach(x=>frame.contentWindow.postMessage({type:'xray-highlight',id:String(state.nodes.indexOf(x))},'*'));info.innerHTML=`CSS selector <b>${esc(selector)}</b> matches ${matches.length} element${matches.length===1?'':'s'}.`;}catch(e){}});
$('#uploadBtn').onclick=()=>$('#file').click();$('#file').onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>load(r.result,f.name);r.readAsText(f)};$('#loadSample').onclick=()=>load($('#sample').value==='basic'?BASIC:INTER,$('#sample').value==='basic'?'Basic HTML Meatball sample':'Interactive Meatball sample');$('#clear').onclick=clearSel;load(BASIC,'Basic HTML Meatball sample');
